### ISSUE TITLE
Conflicting data when using $addToSet and $pull

### ISSUE THREAD

**Issue by Jarskih** [cult-of-coders/redis-oplog#133]
I have simple block helper when using Blaze:

```
{{#if isLiked}} 
{{> liked}}
{{else}}
{{> not_liked}}
{{/if}} 
```

And when user calls Method to like the **post** their **id** will be added to array using **$addToSet**.
I expect template to change from **not_liked** to **liked**

What happens instead is that the helper changes back and forth and causes the templates to change couple of times before settling to **not_liked** or **liked** template.

From console:

> Helper of main page: Is post liked?: true
> Template.liked.onRendered: UserId: ["QjsLLssBYq24DRZRz"]
> Helper of main page: Is post liked?: false
> Template.notliked.onRendered: UserId: []
> Helper of main page: Is post liked?: true
>  Template.liked.onRendered: UserId ["QjsLLssBYq24DRZRz"]

In this case it worked (showed **liked** template) but it is really random which template will be shown at the end.

The app works normally before adding this package and breaks after adding it.

Additionally I cannot seem to turn off overridePublishFunction even though I set it to false?
```
"redisOplog": {
        "redis": {
            "port": 6379,
            "host": "127.0.0.1"
        },
        "debug": true,
        "overridePublishFunction": false
    }
```

What might be happening here?
I am trying to reproduce with simpler code. Will post it if I manage to do it.

**Comment by rajpa** [comment]
hi @Jarskih 

does this problem still exist. were you able to reproduce? 

thanks/rajpa

**Comment by theodorDiaconu** [comment]
@Jarskih @rajpa  I am sure this is related to optimistic-ui. Will look into it.

**Comment by rajpa** [comment]
@theodorDiaconu i am thinking it maybe because of the way addToSet works. an element is added to the array if and only if it does not exist in the set already. redis/oplog may need to do an additional check to see if the element is in the array already. just my guess

thanks/rajpa

**Comment by theodorDiaconu** [comment]
@rajpa it's not that. I've written tests. I think he was not on the latest version ? My tests are passing and no flickers are caused. @Jarskih I need exact state of the document, and the updates you are doing. Otherwise I'm going to close this, since tests are passing.

**Comment by theodorDiaconu** [comment]
This should be fixed in 1.1.8 reopen if it isn't. Thanks

**Comment by rajpa** [comment]
Super!  Thank you!

-- Rajesh Bhaskar

**Comment by Jarskih** [comment]
I can confirm it still happens on my app with newest version. I tried to reproduce by creating new meteor app with this package and using $addToSet the same way. Unfortunately I could not see the same behavior this time.
Do you think it might be caused by incompatibility of this package and some of the packages my app uses. I am currently using https://github.com/chatr/redpubsub for redis and I don't have this problem.

Packages I use (this package and disable-oplog excluded): 

>     
    'meteor-base',
    'mongo',
    'blaze-html-templates',
    'jquery',
    'session',
    'tracker',
    'service-configuration',
    'accounts-ui',
    'accounts-base',
    'accounts-password',
    'check',
    'reactive-var',
    'http',
    'email',
    'shell-server',
    'ecmascript',
    'amplify',
    'aldeed:simple-schema@1.5.3',
    'aldeed:collection2@2.10.0',
    'aldeed:http@0.2.2',
    'aldeed:autoform@5.8.1',
    'aldeed:template-extension@4.1.0',
    'fourseven:scss@4.5.0',
    'softwarerero:accounts-t9n@1.3.4',
    'kadira:flow-router',
    'kadira:blaze-layout@2.3.0',
    'arillo:flow-router-helpers@0.5.2',
    'meteorhacks:picker@1.0.3',
    'mighdy:dochead',
    'dburles:collection-helpers@1.1.0',
    'matb33:collection-hooks@0.8.4',
    'chuangbo:marked@0.3.5_1',
    'staringatlights:fast-render',
    'staringatlights:inject-data',
    'thelohoadmin:subs-manager@1.6.4_2',
    'meteorhacks:inject-initial',
    'percolatestudio:synced-cron@1.1.0',
    'useraccounts:bootstrap@1.14.2',
    'useraccounts:flow-routing@1.14.2',
    'aramk:tinycolor@1.1.0_1',
    'momentjs:moment@2.17.1',
    'sacha:spin@2.3.1',
    'aslagle:reactive-table@0.8.39',
    'utilities:avatar@0.9.2',
    'fortawesome:fontawesome@4.7.0',
    'ccan:cssreset@1.0.0',
    'djedi:sanitize-html@1.11.3',
    'dburles:collection-helpers@1.1.0',
    'jparker:gravatar@0.5.1',
    'sanjo:meteor-files-helpers@1.2.0_1',
    'cmather:handlebars-server@2.0.0',
    'chuangbo:cookie@1.1.0',
    'ongoworks:speakingurl@9.0.0',
    'okgrow:router-autoscroll@0.1.8',
    'tmeasday:publish-counts@0.8.0',
    'utilities:onsubscribed@0.1.2',
    'utilities:menu@0.1.8',
    'standard-minifier-js',
    'seba:minifiers-autoprefixer@1.0.1',
    'dburles:spacebars-tohtml@1.0.1',
    'meteorhacks:unblock@1.1.0'

I will try to test later more.

**Comment by theodorDiaconu** [comment]
@Jarskih I think I know what the issue is, I had it also. I'm now working on some things, but checkout this branch: https://github.com/cult-of-coders/redis-oplog/pull/136
